---
http_interactions:
- request:
    method: post
    uri: https://api-cn.ronghub.com/user/getToken.json
    body:
      encoding: UTF-8
      string: userId=nutzer&name=John+Doe
    headers:
      Rc-App-Key:
      - "<RONGCLOUD_APP_KEY>"
      Rc-Nonce:
      - GQ9JLdoCs6vPI40O
      Rc-Timestamp:
      - '1665633979819'
      Rc-Signature:
      - 5564138ffd5366bd44e8c82d682342649ae9882d
      Connection:
      - close
      Content-Type:
      - application/x-www-form-urlencoded
      Host:
      - api-cn.ronghub.com
      User-Agent:
      - http.rb/5.1.0
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 13 Oct 2022 04:06:21 GMT
      Content-Type:
      - application/json;charset=UTF-8
      Transfer-Encoding:
      - chunked
      Connection:
      - close
      Vary:
      - Accept-Encoding
      - Accept-Encoding
      - Accept-Encoding
      - Accept-Encoding
      X-Request-Id:
      - 3a4f39674d0ed4faa3c5c50c6af42415
    body:
      encoding: UTF-8
      string: '{"code":200,"userId":"nutzer","token":"35Ufb55yCBsDTweUTPFMpD+mwJQXhhmAf3CDyNQrLaw=@5r3v.cn.rongnav.com;5r3v.cn.rongcfg.com"}'
  recorded_at: Thu, 13 Oct 2022 04:06:20 GMT
recorded_with: VCR 6.1.0
