---
http_interactions:
- request:
    method: post
    uri: https://api-cn.ronghub.com/user/getToken.json
    body:
      encoding: UTF-8
      string: userId=nutzer&name=John+Doe
    headers:
      Rc-App-Key:
      - "<RONGCLOUD_APP_KEY>"
      Rc-Nonce:
      - BYwujyL49kmH60Ql
      Rc-Timestamp:
      - '1665656506274'
      Rc-Signature:
      - 0bf2b9170338903048155dea66bf763f41ce04ae
      Connection:
      - close
      Content-Type:
      - application/x-www-form-urlencoded
      Host:
      - api-cn.ronghub.com
      User-Agent:
      - http.rb/5.1.0
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 13 Oct 2022 10:21:48 GMT
      Content-Type:
      - application/json;charset=UTF-8
      Transfer-Encoding:
      - chunked
      Connection:
      - close
      Vary:
      - Accept-Encoding
      - Accept-Encoding
      - Accept-Encoding
      - Accept-Encoding
      X-Request-Id:
      - 525a9a577f5e7ac97e0bfc467335603e
    body:
      encoding: UTF-8
      string: '{"code":200,"userId":"nutzer","token":"35Ufb55yCBsDTweUTPFMpHigiHyBvlXtTVogE1D5Ts0=@5r3v.cn.rongnav.com;5r3v.cn.rongcfg.com"}'
  recorded_at: Thu, 13 Oct 2022 10:21:46 GMT
recorded_with: VCR 6.1.0
